# fly.toml app configuration file generated for datingapp22019098256 on 2024-05-16T15:23:20+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datingapp22019098256'
primary_region = 'jnb'

[build]
  image = 'zintlekomazi22/datingapp:latest'

[env]
  ASPNETCORE_URLS = 'http://+:8080'
  CloudinarySettings__ApiKey = '128938913825563'
  CloudinarySettings__CloudName = 'dbu2awblm'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
